### ISSUE TITLE
hide address in autoloads attributes

### ISSUE THREAD

**Issue by saklar13** [QualiSystems/OpenStack-Cloud-Provider-Shell-2G#15]
```yaml
capabilities:
  auto_discovery_capability:
    type: cloudshell.capabilities.AutoDiscovery
    properties:        
      ...
      hide_address:
        type: string
        default: true
```
